from enum import Enum

class CategoriaEvento(str, Enum):
    MEDIA = "MEDIA"
    SENSOR_SYSTEM_CONTEXT = "SENSOR_SYSTEM_CONTEXT"
    APP_FOREGROUND = "APP_FOREGROUND"
    NOTIFICACAO = "NOTIFICACAO"
    # Categorias para controle interno do sistema
    SISTEMA_PAUSA_INTERACOES = "SISTEMA_PAUSA_INTERACOES"
    SISTEMA_LIBERA_INTERACOES = "SISTEMA_LIBERA_INTERACOES"
    SISTEMA_COMANDO_USUARIO = "SISTEMA_COMANDO_USUARIO"
    MEDIA_COMANDO = "MEDIA_COMANDO"
    INTENCAO_NOTIFICACAO = "INTENCAO_NOTIFICACAO" # Nova categoria
    NOTIFICACAO_PRONTA_PARA_ENVIO = "NOTIFICACAO_PRONTA_PARA_ENVIO"
    SISTEMA_COMANDO_INTERNO = "SISTEMA_COMANDO_INTERNO"
    # NOVAS CATEGORIAS PARA PC
    PC_ACTIVITY = "PC_ACTIVITY"
    SISTEMA_COMANDO_PC = "SISTEMA_COMANDO_PC"
    INTENCAO_PESQUISA = "INTENCAO_PESQUISA"

class TipoAcao(str, Enum):
    NORMAL = "NORMAL"
    INTENCAO_INTERACAO = "INTENCAO_INTERACAO"
    EVENTO_COMPLEXO = "EVENTO_COMPLEXO"
    INTENCAO_RACIOCINIO = "INTENCAO_RACIOCINIO"
    INTENCAO_PESQUISA = "INTENCAO_PESQUISA"
    RESULTADO_PESQUISA = "RESULTADO_PESQUISA"
    GERAR_RESUMO_PERFIL = "GERAR_RESUMO_PERFIL"
    FEEDBACK_USUARIO = "FEEDBACK_USUARIO"
    ATUALIZAR_CONTEXTO = "ATUALIZAR_CONTEXTO"
    # NOVA AÇÃO PARA PC
    EXECUTAR_PROGRAMA = "EXECUTAR_PROGRAMA"

class PrioridadeEvento(int, Enum):
    BAIXA = 1
    NORMAL = 2
    ALTA = 3

class OrigemEvento(str, Enum):
    KERNEL = "KERNEL"
    USUARIO = "USUARIO"
    ANDROID = "ANDROID"
    IA = "IA"
    SISTEMA = "SISTEMA"

class EstadoEvento(str, Enum):
    NOVO = "NOVO"
    PENDENTE = "PENDENTE"
    PROCESSANDO = "PROCESSANDO"
    CONCLUIDO = "CONCLUIDO"

class TipoEntidade(str, Enum):
    ARTISTA = "ARTISTA"
    APP = "APP"
    CONTATO = "CONTATO"
